version: 2.1
orbs:
  # loading orbs from circleCI
  python: circleci/python@1.5.0
  heroku: circleci/heroku@1.2.6

jobs:

  # mount a docker python image to run tests
  build-and-test:
    docker:
      - image: cimg/python:3.9
        environment:
          SECRET_KEY: $SECRET_KEY
    steps:
      - checkout
      # installing packages with pip using orb
      - python/install-packages:
            pkg-manager: pip
      - run:
          name: Run flake8
          command: flake8
      - run:
          name: Run tests
          command: pytest

  # Create docker image of the project, then tag it with "latest" and commit's SHA1
  # then push it to dockerhub
  dockering:
    machine: true
    steps:
      - checkout
      - run:
          name: creating image
          command: docker build -t p13 .
      - run:
          name: taging image
          command: |
            docker tag p13 $DOCKERHUB_USERNAME/p13:${CIRCLE_SHA1}
            docker tag p13 $DOCKERHUB_USERNAME/p13:latest
      - run:
          name: login dockerhub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: pushing to dockerhub
          command: |
            docker push $DOCKERHUB_USERNAME/p13:${CIRCLE_SHA1}
            docker push $DOCKERHUB_USERNAME/p13:latest
      - run:
          name: logout
          command: docker logout


workflows:
  django:
    jobs:
      # always executed
      - build-and-test

      # only execute for master branch, if build-and-test was completed
      - dockering:
          requires:
            - build-and-test
          filters:
            branches:
              only: master

      # only executed for master branch, if dockering was completed
      - heroku/deploy-via-git:
          requires:
            - dockering
          pre-steps:
            - heroku/install
            # setting config vars in heroku, If heroku app is drop, there is
            # no need to enter django's secret key and sentry DSN on heroku again,
            # it's done here.
            - run: |
                heroku config:set SECRET_KEY=${SECRET_KEY} -a ${HEROKU_APP_NAME}
                heroku config:set SENTRY_DSN=${SENTRY_DSN} -a ${HEROKU_APP_NAME}
          filters:
            branches:
              only: master