version: 2.1
orbs:
  python: circleci/python@1.5.0
  heroku: circleci/heroku@1.2.6

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
            pkg-manager: pip
      - run:
          name: Run flake8
          command: flake8
      - run:
          name: Run tests
          command: pytest

  dockering:
    machine: true
    steps:
      - checkout
      - run:
          name: creating image
          command: docker build -t p13 .
      - run:
          name: taging image
          command: docker tag p13 $DOCKERHUB_USERNAME/p13:${CIRCLE_SHA1}
      - run:
          name: login dockerhub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: pushing to dockerhub
          command: docker push nicolasfrenay/p13:${CIRCLE_SHA1}
      - run:
          name: logout
          command: docker logout

#  heroku_deploy:
#    executor: heroku/default
#    steps:
#      - checkout
#      - heroku/install
#      - run:
#          command: heroku/deploy-via-git
            

workflows:
  django:
    jobs:
      - build-and-test

      - dockering:
          requires:
            - build-and-test
          filters:
            branches:
              only: master

      - heroku_deploy:
          jobs:
            - heroku/deploy-via-git:
                - run: python manage.py runserver
          requires:
            - build-and-test
          filters:
            branches:
              only: master
