version: 2.1
orbs:
  python: circleci/python@1.5.0
  heroku: circleci/heroku@1.2.6

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
        environment:
          SECRET_KEY: $SECRET_KEY
    steps:
      - checkout
      - python/install-packages:
            pkg-manager: pip
      - run:
          name: Run flake8
          command: flake8
      - run:
          name: Run tests
          command: pytest

  dockering:
    machine: true
    steps:
      - checkout
      - run:
          name: creating image
          command: docker build -t p13 .
      - run:
          name: taging image
          command: |
            docker tag p13 $DOCKERHUB_USERNAME/p13:${CIRCLE_SHA1}
            docker tag p13 $DOCKERHUB_USERNAME/p13:latest
      - run:
          name: login dockerhub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: pushing to dockerhub
          command: |
            docker push $DOCKERHUB_USERNAME/p13:${CIRCLE_SHA1}
            docker push $DOCKERHUB_USERNAME/p13:latest
      - run:
          name: logout
          command: docker logout

  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: build for heroku
          command: docker build .

      # Deploy to Heroku
      - heroku/install
      - run: heroku container:login
      - heroku/push-docker-image:
          process-types: web
      - heroku/release-docker-image:
          process-types: web


workflows:
  django:
    jobs:
      - build-and-test

      - dockering:
          requires:
            - build-and-test
          filters:
            branches:
              only: master

#      - heroku/deploy-via-git:
      - deploy:
          requires:
            - dockering
#          pre-steps:
#            - heroku/install
#            - run: heroku config:set SECRET_KEY=${SECRET_KEY} -a ${HEROKU_APP_NAME}
          filters:
            branches:
              only: master
