# Generated by Django 3.0 on 2022-03-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20220328_1418'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Profile',
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Profile',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Profile',
                    table='profiles_profile',
                )
            ],
        )
    ]
